# Generated by Django 5.0.1 on 2024-01-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0002_blog_category_blog_cat_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='blog_cat_description',
            field=models.CharField(max_length=200),
        ),
    ]
