# Generated by Django 5.0.1 on 2024-01-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0004_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='u_name',
        ),
    ]
