# Generated by Django 5.0.1 on 2024-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0006_query_u_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='u_email',
            field=models.EmailField(max_length=200),
        ),
    ]
