# Generated by Django 5.0.1 on 2024-01-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0007_alter_query_u_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='u_email',
            field=models.EmailField(max_length=254),
        ),
    ]
