# Generated by Django 5.0.1 on 2024-01-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0008_alter_query_u_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_membership', models.CharField(max_length=60)),
            ],
        ),
    ]
