# Generated by Django 5.0.1 on 2024-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0009_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='u_email',
            field=models.EmailField(max_length=254),
        ),
    ]
