# Generated by Django 5.0.1 on 2024-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0010_alter_subscription_u_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='u_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
